### PR TITLE
Remove unneeded Boost dependencies

### PR DESCRIPTION
**Pull request by ehargitt**
I grep'd through the azmq source to check which Boost modules are actually needed, and I added/removed as necessary. Fails Travis CI xcode job, but everything else passes.

### CODE REVIEW

**Comment by ehargitt** [comment]
Didn't know if I needed to ping anyone, so I'll ping @solvingj

**Comment by solvingj** [comment]
Thanks, sorry for delay, will process this after we get through boost 1690 rebuild. Maybe 1-2 more days. Thanks for pinging, if I fail to follow up by Saturday, can ping again.

**Comment by SSE4** [comment]
@solvingj ping :)

**Comment by SSE4** [comment]
@solvingj I gonna merge this one, any objections?

**Pull request merged**
